/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./src/**/*.{js,ts,jsx,tsx,css}",
    "./src/shadcn/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./layouts/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    'min-h-screen',
    'bg-gray-50',
    'flex',
    'flex-col',
    'justify-center',
    'py-12',
    'sm:px-6',
    'lg:px-8',
    'text-gray-900',
    'bg-white',
    'shadow',
    'sm:rounded-lg',
    'bg-green-600',
    'hover:bg-green-700',
    'focus:ring-green-500',
    'text-green-500',
    'border-gray-300',
    'placeholder-gray-400',
    'disabled:bg-gray-300',
    'disabled:cursor-not-allowed',
    'text-indigo-600',
    'hover:text-indigo-500',
    'bg-background',
    'text-foreground',
    'bg-primary',
    'text-primary',
    'text-primary-foreground',
    'border-border',
    {
      pattern: /(min-h-screen|bg-(gray-50|white|green-600|green-700|background|primary|secondary)|flex|flex-col|justify-center|py-12|px-(6|8)|text-(gray-900|green-500|indigo-600|indigo-500|foreground|primary|primary-foreground)|shadow|rounded-lg|border-(gray-300|border)|placeholder-gray-400|cursor-not-allowed|ring-green-500)/,
      variants: ['sm', 'lg', 'hover', 'focus', 'disabled', 'dark'],
    },
  ],
  theme: {
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    require("@tailwindcss/forms"),
    require("@tailwindcss/typography"),
    function ({ addBase }) {
      addBase({
        "*": { "print-color-adjust": "exact", "color-adjust": "exact" },
        "@media print": { "*": { "print-color-adjust": "exact !important", "color-adjust": "exact !important" } },
      });
    },
  ],
};
